= Failure Considerations for the C (libcouchbase) SDK in Couchbase
:navtitle: Failure Considerations

include::6.0@sdk:shared:partial$env-errors.adoc[tag=failover_definition]

include::6.0@sdk:shared:partial$env-errors.adoc[tag=what_to_expect_in_application]

include::6.0@sdk:shared:partial$env-errors.adoc[tag=what_to_expect_during_failover]

include::6.0@sdk:shared:partial$env-errors.adoc[tag=missing-nodes]

include::6.0@sdk:shared:partial$env-errors.adoc[tag=timeouts]

include::6.0@sdk:shared:partial$env-errors.adoc[tag=network_failures]

[#devguide-replica-read]
== Reading from replicas

High-availability applications can read documents from replicas, exchanging consistency for availability.

If your bucket is configured for replication, then multiple replicas of each item exist within the cluster.
By default the client will attempt to access an item using its computed master or active node.
This returns the current and authoritative version of the item as it is stored within Couchbase.

In conditions where access to the active node is unavailable (for example, it is disconnected from the network), an application may be able to access a replica version of the item using the _get-from-replica_ operation which queries a replica node for a copy of the item.

NOTE: The item received from a replica node may be an older version.
It is possible a newer version exists in the active node, but did not manage to get replicated before the active node went offline.

== Handling unresponsive servers

If a server is unresponsive action should be taken to determine the cause and either fix the server or fail it over, depending on available replicas and the type of problem caused.
The client SDK cannot determine if a server is unresponsive and by default assumes that any network or server failure is extremely temporary in nature and will attempt to reconnect as required.

If a cluster node is unresponsive and the application determines (through a mechanism outside Couchbase) that the node may be unresponsive for some time, it is possible to avoid sending operations to that node:

In Couchbase architecture, keys are mapped to [vBuckets], which in turn are mapped to cluster nodes.
To avoid sending operations to a specific server, you need to retrieve the server index for the key and then the hostname corresponding to that index.
This is done by using the _vBucket_ API:

[source,c]
----
bool maybe_skip_host(lcb_t instance,
                     const std::string& key,
                     const std::vector<std::string>& badhosts) {
    lcbvb_CONFIG *vbc;
    lcb_cntl(instance, LCB_CNTL_GET, &vbc);
    int ix, vbtmp;
    lcbvb_map_key(vbc, keybuf, keylen, &vbtmp, &ix);
    if (ix < 0) {
        // Missing node. See next section!
        return false;
    } else {
        std::string hostname = lcbvb_get_hostname(ix);
        for (size_t ii = 0; ii < badhosts.size(); ++ii) {
            if (hostname == badhosts[ii]) {
                return true;
            }
        }
    }
    return false;
}
----
