= Failure considerations for the C (libcouchbase) SDK in Couchbase
:navtitle: Failure Considerations

include::4.6@sdk:shared:partial$env-errors.adoc[tag=group]

== Handling unresponsive servers

If a server is unresponsive action should be taken to determine the cause and either fix the server or fail it over, depending on available replicas and the type of problem caused.
The client SDK cannot determine if a server is unresponsive and by default assumes that any network or server failure is extremely temporary in nature and will attempt to reconnect as required.

If a cluster node is unresponsive and the application determines (through a mechanism outside Couchbase) that the node may be unresponsive for some time, it is possible to avoid sending operations to that node:

In Couchbase architecture, keys are mapped to [vBuckets], which in turn are mapped to cluster nodes.
To avoid sending operations to a specific server, you need to retrieve the server index for the key and then the hostname corresponding to that index.
This is done by using the _vBucket_ API:

[source,c]
----
bool maybe_skip_host(lcb_t instance,
                     const std::string& key,
                     const std::vector<std::string>& badhosts) {
    lcbvb_CONFIG *vbc;
    lcb_cntl(instance, LCB_CNTL_GET, &vbc);
    int ix, vbtmp;
    lcbvb_map_key(vbc, keybuf, keylen, &vbtmp, &ix);
    if (ix < 0) {
        // Missing node. See next section!
        return false;
    } else {
        std::string hostname = lcbvb_get_hostname(ix);
        for (size_t ii = 0; ii < badhosts.size(); ++ii) {
            if (hostname == badhosts[ii]) {
                return true;
            }
        }
    }
    return false;
}
----
