= Full Text Search (FTS) using the C (libcouchbase) SDK with Couchbase Server
:navtitle: Searching from the SDK

[abstract]
You can use the Full Text Search service (FTS) to create queryable full-text indexes in Couchbase Server.
This page describes how to use Full Text Search using the C SDK.

Couchbase offers Full-Text search support, allowing you to search for documents that contain certain words or phrases.
In the C SDK, you can search full-text indexes by using the row-based [.api]`lcb_fts_query()` API (`#include <libcouchbase/cbft.h>` first, though!)

include::4.5@sdk:shared:partial$experimental-pars.adoc[tag=fts]

To use the [.api]`lcb_fts_query` function, first create an [.api]`lcb_CMDFTS` structure, and populate it with a query.
The query should be specified as a JSON-encoded string and can be generated using any JSON encoder:

[source,c]
----
    std::string encodedQuery(
        "{\"query\":{\"match\":\"hoppy\"},\"indexName\":\"beer-search\",\"size\":10}");
    lcb_CMDFTS cmd = { 0 };
    cmd.callback = rowCallback;
    cmd.query = encodedQuery.c_str();
    cmd.nquery = encodedQuery.size();
----

TIP: See a fully compilable example using FTS from the C SDK: https://github.com/couchbaselabs/devguide-examples/blob/server-4.5/c/fts-basic.cc[^]

[source,c]
----
static void rowCallback(lcb_t, int, const lcb_RESPFTS *resp)
{
    if (resp->rflags & LCB_RESP_F_FINAL) {
        printf("Status: %d\n", resp->rc);
        printf("Meta: %.*s\n", (int)resp->nrow, resp->row);
        if (resp->htresp) {
            printf("HTTP Response: %.*s\n", (int)resp->htresp->nbody, resp->htresp->body);
        }
    } else {
        printf("Row: %.*s\n", (int)resp->nrow, resp->row);
    }
}
----

Note that the `indexName` must be present in the query.

The callback (i.e.
[.api]`lcb_CMDFTS::callback`) is invoked once for each query hit, and one more time (with the [.api]`LCB_RESP_F_FINAL` flag set in the [.api]`lcb_RESPFTS::rflags` field) with the query response metadata.
The metadata contains things such as response xref:full-text-search-overview.adoc#facets[_facets_]

Refer to xref:4.5@server:fts:fts-queries.adoc[Queries] for more information about the encoded query format.
