= Handling Exceptions and other Errors with the C (libcouchbase) SDK in Couchbase
:navtitle: Handling Errors

[abstract]
An error is received if an operation could not be executed.
Sometimes errors are received directly from the server while other times they are generated internally by the client.
This page describes how errors are reported in the C SDK, and how some error types should be handled.

== Error Codes

Most functions in the C SDK return an error code of type [.api]`lcb_error_t`.
As an application developer, you should be prepared to handle non-successful error codes and treat them appropriately.
If the library is not behaving as expected then your first action should be to determine if your application is properly handling (and checking) any error codes returned by the library.
Remember that error codes are only significant when there is an error condition!

A successful operation is defined by the return code of `LCB_SUCCESS`, while any other code indicates an error condition.
You can find a full list of error codes in the [.path]_<libcouchbase/error.h>_ header.

NOTE: New applications are advised to enable extended error codes by using the `LCB_CNTL_DETAILED_ERRCODES` setting (see xref:client-settings.adoc[Client Settings for the C (libcouchbase) SDK with Couchbase Server]).
Extended error codes are not enabled by default to avoid sending older applications error codes that they cannot handle.

== When to Check for Errors, and What They Mean

Success and failure depend on the context.
A successful return code for one of the data operation APIs (for example, [.api]`lcb_store3()`) does not mean the operation itself succeeded and the key was successfully stored.
Rather, it means the key was successfully placed inside the library’s internal queue.
The actual error code is delivered as the [.api]`lcb_RESPBASE::rc` parameter in the operation callback itself (that is, the callback installed with [.api]`lcb_install_callback3()`).

Non-successful error codes received in callbacks are _usually_ a result of a negative server reply or a network connectivity issue.

If an error was returned from a scheduling function (e.g.
[.api]`lcb_get3())`, it may be the result of a bad input (see [.api]`LCB_EIFINPUT`).
Scheduling functions may also return [.api]`LCB_NOT_SUPPORTED` or [.api]`LCB_CLIENT_FEATURE_UNAVAILABLE` which suggest that the server or the client do not support the given API.

If a scheduling API returns anything but `LCB_SUCCESS`, the callback for that specific request will _not_ be delivered.
Conversely, it is guaranteed that the callback will always be delivered if the return code for the scheduling function is `LCB_SUCCESS`.

You can print a textual representation of the error by using [.api]`lcb_strerror`.
This function is always guaranteed to return a valid string

[source,c]
----
lcb_strerror(NULL, LCB_OPTIONS_CONFLICT);
----

NOTE: The first argument to [.api]`lcb_strerror` is ignored and has never been used.

include::6.0@sdk:shared:partial$couchbase-errors.adoc[tag=group]

== Inspecting HTTP (N1QL, MapReduce, FTS) Errors

Many of the SDK's APIs ([.api]`lcb_n1ql_query`, [.api]`lcb_view_query`, [.api]`lcb_fts_query`) use HTTP internally.
Unlike Key-Value based APIs which use a binary protocol and have a fixed internal format for errors, APIs using JSON-over-HTTP can report multiple errors anywhere during execution.
The C SDK itself can only report a single top-level error code (i.e.
the [.param]`rc` within the response structure).

In cases where an HTTP API failed with a non-successful (non-_2xx_) HTTP reply, the [.param]`rc` field will be set to [.api]`LCB_HTTP_ERROR` and the [.api]`LCB_RESP_F_FINAL` bit set in the [.param]`rflags` field.
The _actual_ cause may be determined using one or more of the following mechanisms within the response callback:

* Inspecting the underlying [.api]`lcb_RESPHTTP` object for details.
+
[source,c]
----
if (rv->rc == LCB_HTTP_ERROR && rv->htresp) {
    printf("Underlying HTTP failed with code %d\n", rv->htresp->htstatus);
    printf("Raw payload: %.*s\n", (int)rv->htresp->nbody, rv->htresp->nbody);
}
----
+
`rv` may be [.api]`lcb_RESPN1QL` or [.api]`lcb_RESPVIEWQUERY` or other response types using a row-like API.
Ensure that you verify the [.param]`hresp` pointer is not `NULL` before dereferencing.
Be aware that the content of the response body may be empty or only contain partial JSON.

* Inspecting the row's _metadata_.
The _metadata_ is exposed via the normal row fields (e.g.
[.param]`row`, [.param]`nrow`) of the response structure, but only when the [.api]`LCB_RESP_F_FINAL` bit is set in the [.param]`rflags` field.
+
[source,c]
----
if ((resp->rflags & LCB_RESP_F_FINAL) && resp->nrow) {
    printf("Metadata: %.*s\n", (int)resp->nrow, resp->row);
    json_parse(resp->nrow, resp->row);
}
----
+
The _metadata_ is the raw JSON returned from the server-side API.
It will be emptied out of any row contents (i.e.
any actual result set) as they are dynamically parsed out from the stream.
The metadata may contain errors, warnings, and other metrics which may be useful when debugging.
Unlike the raw HTTP response, the metadata should always be valid JSON.

Note that any error codes other than [.api]`LCB_HTTP_ERROR` indicate that either the C SDK has handled and converted HTTP or metadata-reported errors, or that an error occurred at the transport or input validation layer.
It may still be useful to inspect the raw HTTP response (if any) and/or the metadata as above in such situations.

== Program Crashes and Pitfalls

If your application abnormally terminates while invoking a function with the library, you may have either encountered a bug or passed the library an invalid pointer.
Keep in mind the following points:

* The library is _not_ thread safe.
While you may use multiple _lcb_t_ handles in different threads, you must never access the same handle from multiple threads without using external synchronization functions (such as mutexes).
* The response structures within the callback are valid _only_ in the scope of the callback function itself.
This means you must copy the structure (and any contained keys and values) into another location in memory if you wish to use it outside the callback.
* Callbacks will _not_ be invoked if the scheduling function returns a failure status.
This means that the following code will result in accessing uninitialized memory:
+
[source,c]
----
struct myresult {
  char *value;
  lcb_error_t err;
}
static void get_callback(lcb_t instance, int cbtype, const lcb_RESPGET *resp)
{
  struct myresult *mr = (struct myresult *)resp->cookie;
  mr->err = resp->rc;
  if (mr->err == LCB_SUCCESS) {
    mr->value = malloc(resp->nkey + 1);
    memcpy(mr->value, resp->key, resp->nkey);
    mr->value[resp->nkey] = '\0';
  } else {
    mr->value = NULL;
  }
}

// Some lines later
struct myresult mr;
lcb_get3(instance, &mr, &cmd);
lcb_wait(instance);
if (mr.value) {
  // If lcb_get() returned an error, this will be uninitialized access!
  // ...
}
----

A crash can also be a result of a bug in the library.
Sometimes the library will call abort when it detects an inconsistent state.
If you think you have found a bug in the library you should file a bug in our http://www.couchbase.com/issues/browse/CCBC[issue tracker^] or contact http://support.couchbase.com[Couchbase support^].
When filing a bug, please be sure to include the library version and any relevant code samples.
