= Managing Connections Using the C (libcouchbase) SDK with Couchbase Server
:navtitle: Managing Connections
:page-partial:
:page-topic-type: concept

[abstract]
This section describes how to connect the C SDK to a Couchbase cluster and bucket.
It contains best practices as well as information on the connection string,  SSL and other advanced connection options.

[#RBAC_and_the_SDK]
// tag::RBAC_and_the_SDK[]
== RBAC and the SDK

Couchbase Server 5.0 Enterprise Edition introduced xref:6.0@server:learn:security/authorization-overview.adoc[Authorization].
In order to access cluster-resources, programs, including those supported by the Couchbase SDK, must authenticate with Couchbase Server, and so be identified as existing users, each associated with one or more roles.
Authentication requires the passing of _credentials_; which consist of a _username_ and (in most cases) a _password_.
Users may be defined either locally to Couchbase Server, or externally (for example, by means of an LDAP server).

Once authentication has succeeded, an _authorization_ process checks the roles associated with the identified user.
If role-associated privileges correspond to the level of resource-access requested by the user, access is duly granted; otherwise, it is denied.
// end::RBAC_and_the_SDK[]

== Creating a handle

A library handle is created using the [.api]`lcb_create()` function which accepts an out-pointer to a handle and a parameters structure specifying some core options.

[source,c]
----
lcb_t instance = NULL;
lcb_create_st options;
memset(&options, 0, sizeof options);
options.version = 3;
options.v.v3.connstr = "couchbase://10.3.53.2/my-bucket";
options.v.v3.username = "jo";
options.v.v3.passwd = "s3cr3t";
lcb_error_t rc = lcb_create(&instance, &options);
if (rc != LCB_SUCCESS) {
    printf("Couldn't create handle: %s\n", lcb_strerror(NULL, rc));
}
----

include::6.0@sdk:shared:partial$lcb-pars-shared.adoc[tag=connstr-intro]

[NOTE]
====
From Couchbase C SDK 2.9.1, [.api]`AlternateAddress` is implemented, for connecting to nodes in a NATed environment, such as Docker containers using portmapping. It is on by default, if the server provides a topology that includes a multi-network configuration. Whichever network is selected at bootstrap will be logged. Alternately, choose your network using the connection string:

[source]
----
?network=NAME
----

If using __Docker Swarm__, or otherwise running the SDK inside the NAT, then you will want to disable with `?network=default` in the connection string, or an xref:client-settings.adoc[environmental setting] can be made.

The `default` network is not the same thing as default behavior; default behavior is to compare the hostname/port used to fetch the configuration against the internal address, and if it matches, should use the internal information - and otherwise to choose the external alternate names if available.

Note that any SSL/TLS certificates must be set up at the point where the connections are being made.  The Couchbase SDKs will honor any valid SSL/TLS certificates.

====

Because the C SDK is used as a foundation for other SDKs, it allows for a common connection specification over all those other SDKs.

NOTE: See xref:client-settings.adoc[Client Settings for the C (libcouchbase) SDK with Couchbase Server], which contains some additional connection string options.

When creating a new handle, you can also specify an alternate event loop plugin to use.
This is required if you want to use your library in non-blocking mode with your existing non-blocking application.

Once your handle has been instantiated you may configure it additionally using the [.api]`lcb_cntl()` family of functions.

Note that a successful [.api]`lcb_create` invocation does not mean the handle has been connected to the bucket, but rather that memory has been allocated for the handle so that it may be connected in subsequent calls.

== Connecting a handle

Once a handle has been instantiated it should be connected.
Connecting a handle involves performing the following steps:

. Calling [.api]`lcb_connect` to schedule the connection.
. Yielding to network I/O, either explicitly via [.api]`lcb_wait` or implicitly by returning control to the event loop
. Retrieving the connection status via [.api]`lcb_get_bootstrap_status`.
If running in non-blocking mode, installing the bootstrap callback ([.api]`lcb_get_bootstrap_callback`) should have a similar effect
+
[source,c]
----
lcb_error_t rc;
rc = lcb_connect(instance);
if (rc != LCB_SUCCESS) {
    /* Couldn't schedule connection. Internal issue or problem with the socket */
    printf("Couldn't schedule bootstrap!: %s\n", lcb_strerror(NULL, rc));
    lcb_destroy(instance);
}
lcb_wait(instance);
rc = lcb_get_bootstrap_status(instance);
if (rc != LCB_SUCCESS) {
    printf("Bootstrapping failed: %s\n", lcb_strerror(NULL, rc));
    lcb_destroy(instance);
}
----

Always check the return value of [.api]`lcb_get_bootstrap_status` to ensure the handle is properly connected.
Performing operations on a non-bootstrapped handle will fail with [.api]`LCB_CLIENT_ETMPFAIL`.

== Handle lifetime

The [.api]`lcb_t` object (commonly referred to as _instance_) represents a connection between your application and a Couchbase bucket.
Because the bucket itself may consist of several TCP connections, and because there is a substantial amount of CPU and kernel overhead in creating and destroying these connections, it is recommended that [.api]`lcb_t` objects be kept alive for the lifetime of the application rather than creating and destroying them frequently.

Once the [.api]`lcb_t` is no longer required, you can call [.api]`lcb_destroy()` on it.
The handle should not be destroyed within a callback as it will likely cause it to crash.
Additionally, memory leaks may occur if there are pending uncompleted operations (e.g.
[.api]`lcb_get3`, [.api]`lcb_store3`).

== Configuring the handle

Once the handle is created, it may be xref:client-settings.adoc[configured] by the [.api]`lcb_cntl` and [.api]`lcb_cntl_string` functions.

// tag::group[]

[#ssl]
// tag::ssl[]
== Connecting with SSL

include::6.0@sdk:shared:partial$lcb-pars-shared.adoc[tag=connstr-intro]

Couchbase Sever features the ability to have clients communicate securely via SSL.

To use SSL, you need Couchbase Server Enterprise 3.0 or later (not available in the Community Edition).

. Obtain the SSL certificate used by the Cluster
. Make the certificate available to the file system of the client host.
. Employ the `couchbases://` scheme for the connection string.
. Specify the local path to the certificate as the value for the `certpath` field.

To connect to a bucket on an SSL-enabled Cluster at the node 10.3.4.33, with the certificate saved as `/var/cbcert.pem`:

[source,c]
----
couchbases://10.3.4.33?certpath=/var/cbcert.pem
----
// end::ssl[]

[#multihost]
// tag::multihost[]
== Specifying Multiple Hosts

You can specify multiple hosts in the connection string so that the client may be able to connect even if the cluster topology changed.
To specify multiple hosts, separate them using a comma:

----
couchbase://host1.com,host2.com,host3.com
----

See xref:failure-considerations.adoc[Failure Considerations for the C (libcouchbase) SDK in Couchbase] for more information about handling cluster topology changes.

NOTE: You are not required to enumerate or pass all Couchbase cluster nodes to the client.
The client only needs to know about a _single_ node which is a member of the cluster.
Once the client has connected to the node, it will query that node about the cluster topology, which in turn contains information about all Couchbase nodes and the services they contain.
// end::multihost[]

include::6.0@sdk:shared:partial$dnssrv-pars.adoc[tag=dnssrv]

In the above example, you would specify `couchbase://example.com` as the bootstrap host, and the library would check for the record.
If no such record exists, it will treat `example.com` as an ordinary bootstrap node and try to bootstrap from it.
Note that if you pass more than one bootstrap host, DNS SRV lookup will not be attempted, and the hosts will be interepreted as normal Couchbase nodes.

== IPv6
IPv6 has been supported since Couchbase Data Platform 5.5 (Enterprise Edition), although LCB will use IPv4 by default. 
IPv6 can be specified as allowed or preferred through the connection string `ipv6=allow`, or directly with the C SDK, since version xref:./relnotes-c-sdk.adoc#2-8-3-november-22-2017[2.8.3] of LCB -- see the xref:client-settings.adoc#settings-list[Client Settings] page.


[#configcache]
// tag::configcache[]
== Configuration Cache

In environments when lots of short-lived connections are made to Couchbase (for example, a small command-line utility or a fork-and-execute CGI application) the overhead in actually bootstrapping the client may be significant.
This is because the client must retrieve the configuration from the cluster, and involves several additional TCP requests and in many cases an additional TCP connection.

You can bypass the initial network bootstrap phase by using the `config_cache` directive in the connection string.
The `config_cache` option accepts a path to a local file (the file should not exist when using for the first time).
When performing the bootstrap process, the client will first check the contents of the given file to see if it contains an existing cluster configuration, and if it does, will use the file as the bootstrap source.
If the file does not contain a configuration the client will then retrieve the configuration from the network and then write it to the file, so that future attempts will use the configuration file.

NOTE: The `config_cache` feature is intended only for short-lived connections.
During a cluster-side topology change the client _will_ need to retrieve the configuration from the network as the file-based configuration will become invalid.
// end::configcache[]

== Additional Options

You can pass additional options in the connection string using the URL query format: `couchbase://location-info?option1=value1&option2=value2&optionN=valueN`.
A list of options may be found in xref:client-settings.adoc[Client Settings]

// end::group[]
