= Couchbase C Client Library
:page-topic-type: concept

[abstract]
The C client library (`libcouchbase`) enables you to interface with a Couchbase cluster from within a C or C++ application.

== Compatibility

.Couchbase Server and SDK Supported Version Matrix
|===
| Feature | Server 1.8 | Server 2.0 | Server 2.5 | Server 3.0 | Server 4.0

6+| *Basic Features*

| CRUD Operations
5+| Yes

| MapReduce Views
| No
4+| _Partial_ (Via HTTP transport API).
_Full_ row-based API since 2.4.7

6+| *Advanced Features*

| N1QL Querying
4+| No
| Since 2.5.0

| Fast (CCCP) Bootstrapping
2+| No
3+| Since 2.3.0

| Secure Connections (SSL)
3+| No
2+| Since 2.4.0

6+| *Administrative Features*

| Management Operations
5+| _Partial_ (Via HTTP transport API)
|===

== Contributing

Couchbase welcomes community contributions to the C SDK.
The https://github.com/couchbase/libcouchbase[C SDK source code^] is available on GitHub.
If you would like to contribute code, read the https://github.com/couchbase/libcouchbase/blob/master/CONTRIBUTING.md[CONTRIBUTING^]_.md_ file within the repository.
