= Install and Start Using the C (libcouchbase) SDK with Couchbase Server
:page-partial:
:navtitle: Start Using the SDK
:page-aliases: c-intro,getting-started,hello-couchbase,hello-world:start-using-sdk,concept-docs:http-services
include::partial$attributes.adoc[]

[abstract]
The Couchbase C SDK (`libcouchbase`) enables C and C++ programs to access a Couchbase cluster.
The C SDK is also commonly used as a core dependency of SDKs written in other language to provide a common implementation and high performance.

== Features

* Cross-Platform: Officially supported on _Linux_, _Mac OS X_, and _Microsoft Windows_ (though it is also known to run on other platforms).
* Key-Value (CRUD) operations ([.api]`lcb_get3`, [.api]`lcb_store3`, etc.)
* N1QL query operations ([.api]`lcb_n1ql_query`)
* Map Reduce (view) query operations ([.api]`lcb_view_query`)
* Secure SSL connections (Couchbase Enterprise only)
* Pluggable non-blocking event loops such as *libevent*, *libev*, and *libuv*- integrate with your own non-blocking application, or use [.api]`lcb_wait` in blocking code

Note that SSL and N1QL features depend on server support.
See xref:compatibility-versions-features.adoc[Compatibility] to see which server versions support which features.

// tag::platform_support[]
== Platform support and installation

The Couchbase C SDK can be installed via apt or yum repositories on Linux; homebrew on Mac OS X; and <<install-windows,binary archives for Microsoft Windows>>.
It may also be https://github.com/couchbase/libcouchbase[built from source^] on any of the platforms mentioned above, and more.
// end::platform_support[]

// tag::linux[]
[#install-linux]
== Installing on Linux

For installation on Linux, install the _couchbase-release_ repository, and then install the _libcouchbase_ packages.
The following examples download and install _couchbase-release_ repository, a C and C++ compiler, and the C SDK core (_libcouchbase2-core_), command line tools (_libcouchbase2-bin_), and the development tools (_libcouchbase-devel_ [RPM] or _libcouchbase-dev_ [DEB]).

.Debian and Ubuntu
[source,bash]
----
# Only needed during first-time setup:
wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-6-amd64.deb
sudo dpkg -i couchbase-release-1.0-6-amd64.deb
# Will install or upgrade packages
sudo apt-get update
sudo apt-get install libcouchbase-dev libcouchbase2-bin build-essential
----

Note that as of Couchbase Data Platform 6.0, _couchbase-release_ (1.0.6) supports Debian 7, 8, and 9, and Ubuntu 12.04, 14.04, 16.04, and 18.04. If you wish to install a Couchbase SDK on another Ubuntu or Debian variation, follow these steps (but note that while newer releases may work, other platforms are not necessarily supported):

// tag::new_ubuntu[]
.Adding repo manually
[source,bash]
----
# Install Couchbase's GPG key
sudo wget -O - http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -
# Adding Ubuntu 18.04 repo to apt/sources.list of 18.10 or 19.04
echo "deb http://packages.couchbase.com/ubuntu bionic bionic/main" | sudo tee /etc/apt/sources.list.d/couchbase.list
# To install or upgrade packages
sudo apt-get update
sudo apt-get install libcouchbase-dev libcouchbase2-bin build-essential
----
// end::new_ubuntu[]

.RHEL and CentOS
[source,bash]
----
# Only needed during first-time setup:
wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-6-x86_64.rpm
sudo rpm -iv couchbase-release-1.0-6-x86_64.rpm
# Will install or upgrade existing packages
sudo yum install libcouchbase-devel libcouchbase2-bin gcc gcc-c++
----

NOTE: You should install the `libcouchbase2-libevent` or `libcouchbase2-libev` plugin in case your application will use more than 1024 file descriptors.
The default `select()` based event loop only supports 1024 file descriptors.
// end::linux[]

// tag::macos[]
[#install-osx]
== Installation on Mac OS X

To install the library on Mac OS X, first install the de-facto package manager for OS X: http://brew.sh/[homebrew^].
Once _homebrew_ is configured:

[source,bash]
----
brew update # get list of latest packages
brew install libcouchbase@2
----

[NOTE]
.LCB 2.10 & Homebrew
====
This will install libcouchbase 2 in _keg-only_ mode -- 
meaning it is installed to _Cellar_, but not symlinked in */usr/local*. 
If you have LCB 3.0 also installed on your development machine, you can change the linked version to 2.10.6 with `brew link`:

[source,console]
----
brew unlink libcouchbase
brew link --force --overwrite libcouchbase@2
----

And reverse this when you need to develop on LCB 3.0.
See the https://docs.brew.sh/Tips-N'-Tricks[Homebrew docs] for more on `brew link`.
====
// end::macos[]

[#install-windows]
== Installation on Microsoft Windows


Windows binary packages can be found as downloads for each version listed on the xref:sdk-release-notes.adoc#latest-release[Release Notes and Archives page], 
linked from the table in each Release Note, and categorized by _Visual Studio_ version.
include::sdk-release-notes.adoc[tag=windows-installation]

If for some reason you cannot use any of the prebuilt Windows binaries, you may install from source -- see the next section:


== Installing from Source Code

You may install the library from source either by downloading a source archive, 
or by checking out the https://github.com/couchbase/libcouchbase[git repository^].
Follow the instructions in the archive's https://github.com/couchbase/libcouchbase/blob/master/README.markdown[README^] for further instructions.

Source archives can be found as a download for each version of the C SDK listed on the xref:sdk-release-notes.adoc#latest-release[Release Notes and Archives page], linked from the table in each Release Note.


== Documentation and Examples

* A reference guide (this manual) is suitable for a general overview and learning how to use the library.
* The {lcb-api-link}[API documentation^] is generated from comments in the header and covers all the APIs of the library.
* Small standalone examples can be found in the https://github.com/couchbase/libcouchbase/tree/master/example[github repository^].
* Other Couchbase SDKs are written on top of the C SDK and show more complex usage of the library's features:
 ** https://github.com/couchbase/couchbase-python-client[Python SDK^]
 ** https://github.com/couchbase/couchnode[Node.js SDK^]
* The library's own `cbc` (https://github.com/couchbase/libcouchbase/blob/master/tools/cbc.cc[^]) and `cbc-pillowfight` (https://github.com/couchbase/libcouchbase/blob/master/tools/cbc-pillowfight.cc[^]) utilities.
Note that these tools may use internal APIs not intended for public use.
* C++11 wrapper (https://github.com/couchbaselabs/libcouchbase-cxx[^], _not officially supported_)

Information on new features, fixes, known issues as well as information on how to install older release versions is available in the xref:sdk-release-notes.adoc[release notes].

== Hello Couchbase

The simple example below (which requires version 2.5.6 or higher to function) can be integrated into an existing application, or added to a CLI skeleton to make a demo app.
Error checking is omitted for brevity.

[source,c]
----
#include <string.h>
#include <libcouchbase/couchbase.h>

static void
opCallback(lcb_t instance, int cbtype, const lcb_RESPBASE *rb) {
    fprintf(stderr, "%.*s: %s... ", (int)rb->nkey, rb->key, lcb_strcbtype(cbtype));
    if (rb->rc != LCB_SUCCESS) {
        fprintf(stderr, "%s\n", lcb_strerror(NULL, rb->rc));
    } else {
        fprintf(stderr, "OK");
        if (cbtype == LCB_CALLBACK_GET) {
            const lcb_RESPGET *rg = (const lcb_RESPGET *)rb;
            fprintf(stderr, "... Value: %.*s\n", (int)rg->nvalue, rg->value);
        } else {
            fprintf(stderr, "\n");
        }
    }
}

int storeAndRetrieveKey()
{
    assert(lcb_version_g >= 0x020506 && "This example requires 2.5.6 or greater");

    lcb_t instance;
    struct lcb_create_st options;
    memset(&options, 0, sizeof options);
    options.version = 3;
    options.v.v3.connstr = "couchbase://localhost/bucketname";
    options.v.v3.username = "mark";
    options.v.v3.passwd = "s3cr3t";
    lcb_error_t rc = lcb_create(&instance, &options);
    lcb_connect(instance);
    lcb_wait(instance);

    lcb_install_callback3(instance, LCB_CALLBACK_GET, opCallback);
    lcb_install_callback3(instance, LCB_CALLBACK_STORE, opCallback);

    lcb_CMDSTORE scmd = { 0 };
    LCB_CMD_SET_KEY(&scmd, "key", 3);
    LCB_CMD_SET_VALUE(&scmd, "true", 4);
    scmd.operation = LCB_SET;
    lcb_store3(instance, NULL, &scmd);
    lcb_wait(instance);

    lcb_CMDGET gcmd = { 0 };
    LCB_CMD_SET_KEY(&gcmd, "key", 3);
    lcb_get3(instance, NULL, &gcmd);
    lcb_wait(instance);
    lcb_destroy(instance);

    return 0;
}
----

== Scheduling, Blocking and non-blocking

The library is designed to be non-blocking.
As opposed to a blocking API where API calls themselves perform the operations and return results, the C SDK's non-blocking API _schedules_ the operation, with the result of the operation being passed to a callback which is invoked when ready.
The readiness and completion of an operation will only happen when the library has had a chance to send the operation to the server and await a response from the network.

Most operations in the library do not _execute_ the operation immediately, but rather _schedule_ it to be executed when it is possible to perform network I/O.

The [.api]`lcb_wait()` function will instruct the library to send all scheduled operations to the cluster and await the results for those operations.
As results become available, designated callbacks (specified using [.api]`lcb_install_callback3()`) are invoked with the results.

If your application is built on top of an event loop (for example, _libev_) you can integrate the C SDK to perform its I/O within the context of your event loop, avoiding the need to block for I/O with [.api]`lcb_wait()`.

== Library Handle and Server Connections

Almost all operations within the library are done with a library handle of type [.api]`lcb_t`.
The [.api]`lcb_t` is a handle representing a connection to a single bucket (though it is possible to access other buckets as well for certain operations).

An [.api]`lcb_t` is created using the [.api]`lcb_create()` function.
Once created the handle must be connected: [.api]`lcb_connect()` schedules the connection and [.api]`lcb_wait` waits for the connection to complete.
Once [.api]`lcb_wait` returns, [.api]`lcb_get_bootstrap_status` may be used to determine if the connection completed successfully.

IMPORTANT: Any Cluster nodes addresses passed in to establish (bootstrap) the connection should be for data (KV) nodes.

Note: If you have an environment with port mapping, such as Couchbase Server and the SDK in separate containers under Kubernetes, see the multi-network configuration _note_ under xref:managing-connections.adoc#connecting-to-a-bucket[Managing Connections]

Once the handle has been successfully connected it may then be used for data access.

When the library handle is no longer needed, it can be destroyed via [.api]`lcb_destroy()`.

== API Reference

The API reference is generated for each version.
The API reference for version `{lcb-current-version}` is at {lcb-api-link}[]
