= Choosing an API
:navtitle: Choosing an API
:page-topic-type: howto
:page-aliases: ROOT:async-programming,ROOT:batching-operations

[abstract]
Async & batching


Libcouchbase is an asynchronous client that may also be used in blocking mode.
The library contains I/O plugins for common libraries such as _libevent_, _libev_, and _libuv_, and a libevent-based example can be found https://docs.couchbase.com/sdk-api/couchbase-c-client/example_2libeventdirect_2main_8c-example.html[here].

Batching examples are given for https://github.com/couchbase/docs-sdk-c/blob/release/3.1/modules/devguide/examples/c/bulk-store.cc[bulk store] and for https://github.com/couchbase/docs-sdk-c/blob/release/3.1/modules/devguide/examples/c/bulk-get.cc[bulk get].

== Usage Differences in Non-Blocking Mode

For the most part, programming with libcouchbase is the same regardless of whether you're using it in a blocking or non-blocking application.
There are some key differences to note, however:

* [.api]`lcb_wait()` should not be called in non-blocking mode.
By definition, the [.api]`lcb_wait()` routine will block the application until all pending I/O completes.
In non-blocking mode the pending I/O is completed when control is returned back to the event loop.
* You must not schedule operations until the bootstrap callback, [.api]`lcb_set_bootstrap_callback()`, has been invoked.
This is because operations must be forwarded to a destination node in the cluster depending on the key specified within the operation.
Until the client has been bootstrapped it does not know how to forward keys to any nodes.
+
Unlike blocking mode where you may simply do:
+
[source,c]
----
lcb_connect(instance);
lcb_wait(instance);
if (lcb_get_bootstrap_status(instance) == LCB_SUCCESS)) {
  // Start operations
}
----
+
You need to use the callback variant that notifies your application when the library is ready.

* You are responsible for ensuring that the `iops` structure passed to the library remains valid until [.api]`lcb_destroy` is invoked.
Likewise, you are responsible for freeing the `iops` structure via [.api]`lcb_destroy_io_opts()` when it is no longer required.
* Currently the library does blocking DNS look-ups via the standard [.api]`getaddrinfo()` call.
Typically this should not take a long time but may potentially block your application if an invalid host name is detected or the DNS server in use is slow to respond.

== Batching

The most simplistic bulk fetch looks like this:

[source,c]
----
include::example$bulk-get.cc[tag=batching,indent=0]
----
