= Key Value Operations
:navtitle: KV Operations
:page-topic-type: howto
:page-aliases: document-operations.adoc
:page-toclevels: 2

////
The complete code sample used on this page can be downloaded from
///  xref::example$document.cs[here]
- from which you can see in context how to authenticate and connect to a Couchbase Cluster, then perform these Bucket operations.
////

== Documents

A _document_ refers to an entry in the database (other databases may refer to the same concept as a _row_).
A document has an ID (_primary key_ in other databases), which is unique to the document and by which it can be located.
The document also has a value which contains the actual application data.
See xref:concept-docs:documents.adoc[the concept guide to _Documents_] for a deeper dive into documents in the Couchbase Data Platform.
Or read on, for a hands-on introduction to working with documents from the .NET SDK.

== CRUD Operations

The core interface to Couchbase Server is simple KV operations on full documents.
Make sure you're familiar with the basics of authorization and connecting to a Cluster from the xref:hello-world:start-using-sdk.adoc[Start Using the SDK section].

See the {lcb_doc_src_link}/modules/devguide/examples/c/retrieving.cc[code sample^] for use in context.

== Upsert

[TIP]
.Sub-Document Operations
====
All of these operations involve fetching the complete document from the Cluster.
Where the number of operations or other circumstances make bandwidth a significant issue, the SDK can work on just a specific _path_ of the document with xref:subdocument-operations.adoc[Sub-Document Operations].
====

////
== Retrieving full documents

Using the `Get()` method with the document key can be done in a similar fashion to the other operations:

[source,csharp]
----
var result = await collection.Get("document-key");
var content = result.ContentAs<string>();
----

Timeout can also be set - as in the earlier `Insert` example:

[source,csharp]
----
Get (with options)
var result = await collection.Get("document-key",
    new GetOptions
    {
        Timeout = TimeSpan.FromSeconds(5)
    }
);
var content = result.ContentAs<string>();
----


== Removing

When removing a document, you will have the same concern for durability as with any additive modification to the Bucket:

Remove (with options)
[source,csharp]
----
var result = await collection.Remove("document-key",
    new RemoveOptions
    {
        Cas = 12345,
        PersistTo = PersistTo.One,
        ReplicateTo = ReplicateTo.One,
        Timeout = TimeSpan.FromSeconds(5)
    }
);
----
////

Here is a simple upsert operation, which will insert the document if it does not exist, or replace it if it does.

We use `lcb_cmdstore_create` for storing an item in Couchbase as it is only one operation with different set of
attributes/constraints for storage modes.
[source,c]
----
include::example$insert-upsert.cc[tag=upsert]
----

== Insert

Insert works very similarly to upsert , but will fail if the document already exists.
[source,c]
----
include::example$insert-upsert.cc[tag=insert]
----

== Retrieving documents

We've tried upserting and inserting documents into the Couchbase Server, let's get them back:
[source,c]
----
include::example$insert-upsert.cc[tag=retrieve]
----
== Replace

A very common sequence  of operations is to `get` a document, modify its contents, and `replace` it.
// Insert code sample here
So what is CAS?

CAS, or  Compare and  Swap, is a form of optimistic locking. Every  document is Couchbase has a CAS value,
and it's changed on every mutation. When you get a document you also get the document's CAS, and then when it
is time to write the document, you send the same CAS back. If another thread or program has  modified that document
in the  meantime, the  Couchbase Server can detect you've provided a now-outdated CAS, and return an error. This provides
cheap and safe concurrency. See this xref:concurrent-document-mutations.adoc[this detailed description of CAS] for further details.

In general, you'll want to provide a CAS value whenever you `replace` a document, to prevent overwriting another agent's mutations.

Setting a Compare and Swap (CAS) value is a form of optimistic locking - dealt with in depth in the xref:concurrent-document-mutations.adoc[CAS page].
Here we just note that the CAS is a value representing the current state of an item; each time the item is modified, its CAS changes.
The CAS value is returned as part of a document’s metadata whenever a document is accessed.
Without explicitly setting it, a newly-created document would have a CAS value of _0_.
////
_Timeout_ is an optional parameter which in the .NET SDK has a type value of `TimeSpan`.
Timeout sets the timeout value for the underlying network connection.
We will add to these options for the _Replace_ example:

[source,csharp]
----
var document = new {foo = "bar", bar = "foo"};
var result = await collection.Replace("document-key", document,
    new ReplaceOptions
    {
        Cas = 12345,
        Expiration = TimeSpan.FromMinutes(1),
        Timeout = TimeSpan.FromSeconds(5)
    }
);
----

Expiration sets an explicit time to live (TTL) for a document.
We'll discuss modifying `Expiration` in more details xref:#expiration-ttl[below].
For a discussion of item (Document) _vs_ Bucket expiration, see the
xref:7.1@server:learn:buckets-memory-and-storage/expiration.adoc#expiration-bucket-versus-item[Expiration Overview page].

[source,csharp]
----
var document = new {foo = "bar", bar = "foo"};
var result = await collection.Upsert("document-key", document,
    new UpsertOptions
    {
        Cas = 12345,
        Expiration = TimeSpan.FromMinutes(1),
        PersistTo = PersistTo.One,
        ReplicateTo = ReplicateTo.One,
        Timeout = TimeSpan.FromSeconds(5)
    }
);
----

Here, we have add _Durability_ options, namely `PersistTo` and `ReplicateTo`.
////
[source,c]
----
include::devguide:example$c/cas.cc[tag=cas]
----

See the {lcb_doc_src_link}/modules/devguide/examples/c/cas.cc[code sample^] for use in context.
////
In Couchbase Server releases before 6.5, Durability was set with these two options -- see the xref:https://docs.couchbase.com/dotnet-sdk/2.7/durability.html[6.0 Durability documentation] -- covering  how many replicas the operation must be propagated to and how many persisted copies of the modified record must exist.
Couchbase Data Platform 6.5 refines these two options, with xref:6.5@server:learn:data/durability.adoc[Synchronous Replication] -- although they remain essentially the same in use -- see xref:#durability[Durability, below].
////



== Durability
Writes in Couchbase are written to a single node, and from there the Couchbase Server will take care of sending that mutation to any configured replicas.

The optional `durability` parameter, which all mutating operations accept, allows the application to wait until this replication (or persistence) is successful before proceeding.
////
It can be used like this:

[source,c]
----
// durability kv snippet
----
See the {lcb_doc_src_link}/modules/devguide/examples/c/durability.cc[code sample^] for use in context.

If no argument is provided the application will report success back as soon as the primary node has acknowledged the mutation in its memory.
However, we recognize that there are times when the application needs that extra certainty that especially vital mutations have been successfully replicated,
and the other durability options provide the means to achieve this.

The options differ depend on what Couchbase Server version is in use.
If 6.5 or above is being used, you can take advantage of the xref:concept-docs:durability-replication-failure-considerations.adoc#durable-writes[Durable Write] feature,
in which Couchbase Server will only return success to the SDK after the requested replication level has been achieved.
The three replication levels are:

 * `Majority` - The server will ensure that the change is available in memory on the majority of configured replicas.
 * `MajorityAndPersistToActive` - Majority level, plus persisted to disk on the active node.
 * `PersistToMajority` - Majority level, plus persisted to disk on the majority of configured replicas.

The options are in increasing levels of safety.
Note that nothing comes for free - for a given node, waiting for writes to storage is considerably slower than waiting for it to be available in-memory.
These trade offs, as well as which settings may be tuned, are discussed in the xref:concept-docs:durability-replication-failure-considerations.adoc#durable-writes[durability page].

If a version of Couchbase Server lower than 6.5 is being used then the application can fall-back to xref:concept-docs:durability-replication-failure-considerations.adoc#older-server-versions['client verified' durability.]
Here the SDK will do a simple poll of the replicas and only return once the requested durability level is achieved.
This can be achieved like this:

[source,c]
----
include::example$durability.cc[tag=durability]
----
To stress, durability is a useful feature but should not be the default for most applications, as there is a performance consideration,
and the default level of safety provided by Couchbase will be reasonable for the majority of situations.

== Expiration / TTL

Couchbase Server includes an option top have particular documents automatically expire after a set time. This can be useful is some use cases,
such as user sessions, caches, or other temporary documents.

You can set an expiry value to `lmd_cmdstore_expiry` when creating a document:
[source,c]
----
include::example$expiration.cc[tag=expiration]
----

[source,csharp]
----
var result = await collection.Touch("document-key", TimeSpan.FromSeconds(10));
----

A network timeout can be set with the optional `TouchOptions()`, in the same fashion as earlier examples on this page:

[source,csharp]
----
var result = await collection.Touch("document-key", TimeSpan.FromSeconds(30),
    new TouchOptions
    {
        Timeout = TimeSpan.FromSeconds(5)
    }
);
----
////

See the {lcb_doc_src_link}/modules/devguide/examples/c/expiration.cc[code sample^] for use in context.




== Atomic Counters

The numeric content of a document can be manipulated using {lcb_api_link}/group__lcb-counter.html[lcb_RESPCOUNTER^]. Counter opeations treat the document
as a numeric value (the document must contain a parseable integer as its content). This value may then be incremented
or decremented.
[source,c]
----
include::devguide:example$c/counter.cc[tag=atomic-counter]
----
////
.Increment
[source,csharp]
----
// increment binary value by 1, if document doesn’t exist, seed it at 1000
await collection.Binary.Increment("document-key", 1, 1000);
----

[source,csharp]
----
.Increment (with options)
// increment binary value by 1, if document doesn’t exist, seed it at 1000
// optional arguments:
// - Timeout (TimeSpan)
// - Expiration (TimeSpan)
// - CAS (ulong)

await collection.Binary.Increment("document-key", 1, 1000, TimeSpan.FromSeconds(5), TimeSpan.FromDays(1), cas);
----

.Decrement
[source,csharp]
----
// decrement binary value by 1, if document doesn’t exist, seed it at 1000
await collection.Binary.Decrement("document-key", 1, 1000);
----

.Increment (with options)
[source,csharp]
----
// decrement binary value by 1, if document doesn’t exist, seed it at 1000
// optional arguments:
// - Timeout (TimeSpan)
// - Expiration (TimeSpan)
// - CAS (ulong)
await collection.Binary.Decrement("document-key", 1, 1000, TimeSpan.FromSeconds(5), TimeSpan.FromDays(1), cas);
----
////

See the {lcb_doc_src_link}/modules/devguide/examples/c/counter.cc[code sample^] for use in context.

NOTE: Increment & Decrement are considered part of the ‘binary’ API and as such may still be subject to change


include::7.1@sdk:shared:partial$atomic.adoc[tag=xdcr]


== Additional Resources

Working on just a specific path within a JSON document will reduce network bandwidth requirements - see the xref:subdocument-operations.adoc[Sub-Document] pages.
For working with metadata on a document, reference our xref:sdk-xattr-example.adoc[Extended Attributes] pages.

// Another way of increasing network performance is to _pipeline_ operations with xref:concurrent-async-apis.adoc#batching[Batching Operations].

// As well as various xref:concept-docs:data-model.adoc[Formats] of JSON, Couchbase can work directly with xref:concept-docs:nonjson.adoc[arbitary bytes, or binary format].

Our xref:n1ql-queries-with-sdk.adoc[Query Engine] enables retrieval of information using the SQL-like syntax of {sqlpp} (formerly N1QL).
