= MapReduce Views Using the C SDK with Couchbase Server
:navtitle: MapReduce Views
:page-topic-type: howto
:page-aliases: ROOT:view-queries-with-sdk

[abstract]
You can use MapReduce views to create queryable indexes in Couchbase Data Platform.


include::6.5@sdk:shared:partial$views.adoc[tag=views-intro]


You can find further information https://docs.couchbase.com/sdk-api/couchbase-c-client/group__lcb-view-api.html[in the API docs].

== Querying Views

View operations are accessible via `lcb_CMDVIEW`.
Once you have a reference to the bucket you need to at least supply the name of the design document and the name of the view:

[source,c]
----
include::example$views.cc[tag=views,indent=0]
----
== Working with View Rows
In the C client library, query results are delivered on a per-row basis to a given callback, which is specified at query time.
[source,c]
----
include::example$views.cc[tag=view-rows,indent=0]
----
The callback is invoked for each row. The end of the query is signaled by having the `LCB_RESP_F_FINAL` bit set in the response's field.

The response structure contains a `key` and `nkey`,`docid` and `ndocid` fields that contain the buffer and lengths for the  emitted keys of the view result and corresponding document ID.
All the fields (except `docid`) are JSON encoded and should be decoded by a JSON decoder before use.

== Accessing View metadata
The callback function (`lcb_VIEW_CALLBACK`) will contain the `LCB_RESP_F_FINAL` flag set after all the rows have been returned.
Applications should check for the presence of this flag.
If this flag is present, the row itself will contain the raw response metadata in its value field.

////
include::6.5@sdk:shared:partial$views.adoc[tag=example-beer]


[source,csharp]
----
var result = bucket.ViewQuery<Beer>("beers", "by_name", options => {
    options.WithStartKey("A");
    options.WithLimit(10);
});
----

include::6.5@sdk:shared:partial$views.adoc[tag=example-travel]


[source,csharp]
----
var result = bucket.ViewQuery<Landmark>("landmarks", "by_name", options => {
    options.WithKey("<landmark-name>");
});
----

include::6.5@sdk:shared:partial$views.adoc[tag=example-geo-travel]


(10)
);

foreach (var row in result.Rows)
{
    var id = row.Id;
    var key = row.Key;
    var value = row.Value;
}
----

// We only need the briefest of samples - the content brought in at the top of the page will recommend avoiding Views.[source,javascript]
----
function (doc, meta) {
    if (doc.type && doc.type == "landmark" && doc.geo) {
        emit([doc.geo.lon, doc.geo.lat], null);
    }
}
----


== Querying Views through the .NET SDK




Once you have a view defined, it can be queried from the .NET SDK by using the `ViewQuery` method on a Bucket instance.

Here is an example:

[source,csharp]
----
var result = bucket.ViewQuery<Type>("design-doc", "view-name", options =>
    options.WithLimit
////
