= Compatibility of Couchbase Features, Couchbase Server Versions, and the Couchbase C SDK
:description: Features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:navtitle: Compatibility
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features

[abstract]
{description}

// add notes on APIs, C standards, &co.


== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the C SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*:This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="35,30,25,20"]
|===
| |SDK 3.0, 3.1 | 3.2 | 3.3

| *Server 6.0*
| *✔*
| *✔*
| *◎*


| *Server 6.5-6.6*
| *✔*
| *✔*
| *✔*

| *Server 7.0*
| *◎*
| *✔*
| *✔*

| *Server 7.1*
| *◎*
| *◎*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

=== Capella Compatibility

At time of release, the Couchbase 3.3 C SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
Note, LCB does not bundle the Capella Client Certificate, follow the xref:server:guides:connect.adoc#tls[instructions] to download and install the certificate from Capella, then guide to xref:howtos:managing-connections.adoc#ssl[secure connections with LCB].


== Platform Compatibility

Libcouchbase (the C SDK) is tested and supported on the following platforms:

****
[discrete]
=== GNU/Linux

* Amazon Linux 2.
* Red Hat Enterprise Linux 7 & 8;
* CentOS 7 & 8.
* Ubuntu (LTS) 16.04 (_Xenial_), 18.04 (_Bionic_), & 20.04 (_Focal_).
* Debian 9 (_Stretch_) & 10 (_Buster_).
* Alpine Linux

[discrete]
=== Microsoft Windows

Any MS-supported version compatible with Visual Studio 2015 (VC14) or 2017 (VC15).

[discrete]
=== Mac OS X

The current and previous two releases of OS X.
At time of writing (April 2022): 10.15 (_Catalina_), 11 (_Big Sur_), and 12 (_Monterey_).
M1 ARM  architecture is fully supported in the 3.3 C SDK.
****

Although installable or compilable on many other platforms, we cannot provide support for untested combinations.

=== ARM Processor Support

Python 4.0 SDK supports AWS Amazon Graviton2 and Apple M1 ARM processors.


== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells] 
[cols="7,5,6,5"]
|===
| | Server 6.0 | Server 6.5 & 6.6 | Server 7.0 & 7.1

| Enhanced Durability
3+| All SDK versions

| Durable Writes 
| Not Supported
2+| Since 3.0

| Analytics
3+| Since 2.10

| Distributed ACID Transactions
| Not Supported
2+| C++ Transactions 1.0.0 with Server 6.6 and upwardsfootnote:[{cpp} Transactions installs its own version of LCB.]

| Default Collections
| Not Supported
| Developer Preview in 6.5-6.6, SDK 3.0
| Since 3.0.6

| Scope-Level N1QL Queries & all Collections features
2+| Not Supported
| Since SDK 3.2.0

| Request Tracing
| Not Supported
2+| Since SDK 3.0.2
|===

include::{cb_server_version}@sdk:shared:partial$network-requirements.adoc[]

include::{cb_server_version}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]

include::{version-server}@sdk:shared:partial$api-version.adoc[tag=api-version]

include::7.1@sdk:shared:partial$archive.adoc[tag=link]
