= Errors & Exceptions Reference
:nav-title: Error Codes
:page-topic-type: ref

[abstract]
The standardized error codes returned by the Couchbase C SDK, from cloud connection to sub-document.

include::6.5@sdk:shared:partial$error-ref.adoc[tag=intro]

== Shared Error Definitions 

include::6.5@sdk:shared:partial$error-ref.adoc[tag=shared]


== KeyValue Error Definitions
include::6.5@sdk:shared:partial$error-ref.adoc[tag=kv]


== Query Error Definitions
include::6.5@sdk:shared:partial$error-ref.adoc[tag=query]


== Analytics Error Definitions
include::6.5@sdk:shared:partial$error-ref.adoc[tag=analytics]


== Search Error Definition
include::6.5@sdk:shared:partial$error-ref.adoc[tag=search]


== View Error Definitions
include::6.5@sdk:shared:partial$error-ref.adoc[tag=views]


== Management API Error Definitions
include::6.5@sdk:shared:partial$error-ref.adoc[tag=mgmnt]


== Field-Level Encryption Error Definitions
include::6.5@sdk:shared:partial$error-ref.adoc[tag=fle]


////
=== SDK-Specific Error Definitions

ID Range 1000 - 2000

This range is reserved for sdk-specific error codes which are not standardized, but might be used later.
////



== Connecting to Cloud
include::6.5@sdk:shared:partial$error-ref.adoc[tag=cloud]

[source,terminal] 
----
54ms [I5afdccc413f7d46] {81150/307} [ERROR] (connection - L:503) <8676842d-4e8b-4c5b-a44f-e0886f8c0bc1.dp.cloud.couchbase.com:11207> (SOCK=a683f97effd6323c) Couldn't look up 8676842d-4e8b-4c5b-a44f-e0886f8c0bc1.dp.cloud.couchbase.com (nodename nor servname provided, or not known) [EAI=8]
----

[source,terminal] 
----
54ms [I5afdccc413f7d46] {81150/307} [ERROR] (connection - L:164) <8676842d-4e8b-4c5b-a44f-e0886f8c0bc1.dp.cloud.couchbase.com:11207> (SOCK=a683f97effd6323c) Failed to establish connection: LCB_ERR_UNKNOWN_HOST (1049), os errno=0
----

[source,terminal] 
----
54ms [I5afdccc413f7d46] {81150/307} [DEBUG] (lcbio_mgr - L:349) <8676842d-4e8b-4c5b-a44f-e0886f8c0bc1.dp.cloud.couchbase.com:11207> (HE=0x7fa82f4252e0) Received result for I=0x7fa82f426d40,C=0x0; E=0x419
----

.Could not get configuration
[source,terminal] 
----
54ms [I5afdccc413f7d46] {81150/307} [ERROR] (cccp - L:171) <NOHOST:NOPORT> (CTX=0x0,) Could not get configuration: LCB_ERR_UNKNOWN_HOST (1049)
----

.Provider 'CCCP' failed
[source,terminal] 
----
54ms [I5afdccc413f7d46] {81150/307} [INFO] (confmon - L:196) Provider 'CCCP' failed: LCB_ERR_UNKNOWN_HOST (1049)
----

[source,terminal] 
----
54ms [I5afdccc413f7d46] {81150/307} [DEBUG] (confmon - L:240) Will try next provider in 0us
----

[source,terminal] 
----
54ms [I5afdccc413f7d46] {81150/307} [TRACE] (confmon - L:285) Attempting to retrieve cluster map via HTTP
----

[source,terminal] 
----
54ms [I5afdccc413f7d46] {81150/307} [TRACE] (htconfig - L:359) Starting HTTP Configuration Provider 0x7fa82f406730
----

.Timeout=2000000us
[source,terminal] 
----
54ms [I5afdccc413f7d46] {81150/307} [INFO] (connection - L:487) <8676842d-4e8b-4c5b-a44f-e0886f8c0bc1.dp.cloud.couchbase.com:18091> (SOCK=385c8688a482c7bd) Starting. Timeout=2000000us
----

.Couldn't look up ... (nodename nor servname provided, or not known)
[source,terminal] 
----
55ms [I5afdccc413f7d46] {81150/307} [ERROR] (connection - L:503) <8676842d-4e8b-4c5b-a44f-e0886f8c0bc1.dp.cloud.couchbase.com:18091> (SOCK=385c8688a482c7bd) Couldn't look up 8676842d-4e8b-4c5b-a44f-e0886f8c0bc1.dp.cloud.couchbase.com (nodename nor servname provided, or not known) [EAI=8]
----

.Failed to establish connection: LCB_ERR_UNKNOWN_HOST (1049), os errno=0
[source,terminal] 
----
55ms [I5afdccc413f7d46] {81150/307} [ERROR] (connection - L:164) <8676842d-4e8b-4c5b-a44f-e0886f8c0bc1.dp.cloud.couchbase.com:18091> (SOCK=385c8688a482c7bd) Failed to establish connection: LCB_ERR_UNKNOWN_HOST (1049), os errno=0
----

.Connection to REST API failed with LCB_ERR_UNKNOWN_HOST
[source,terminal] 
----
55ms [I5afdccc413f7d46] {81150/307} [ERROR] (htconfig - L:309) Connection to REST API failed with LCB_ERR_UNKNOWN_HOST (1049) (os errno = 0)
----

.Provider 'HTTP' failed
[source,terminal] 
----
55ms [I5afdccc413f7d46] {81150/307} [INFO] (confmon - L:196) Provider 'HTTP' failed: LCB_ERR_UNKNOWN_HOST (1049)
----

.Maximum provider reached. Resetting index
[source,terminal] 
----
55ms [I5afdccc413f7d46] {81150/307} [TRACE] (confmon - L:245) Maximum provider reached. Resetting index
----

.Failed to bootstrap
[source,terminal] 
----
55ms [I5afdccc413f7d46] {81150/307} [ERROR] (bootstrap - L:196) Failed to bootstrap client=0x7fa82f405cd0. Error=LCB_ERR_NO_MATCHING_SERVER (1010) (Last=LCB_ERR_UNKNOWN_HOST (1049)), Message=No more bootstrap providers remain
----

.Couldn't bootstrap from cluster
[source,terminal] 
----
Couldn't bootstrap from cluster. Received code 0x419 (LCB_ERR_UNKNOWN_HOST (1049))
----


== Further Reading

* Our practical look at xref:howtos:error-handling.adoc[error handling with the SDK].
// * xref:howtos:health-check.adoc#diagnostics[Diagnostics] with Health Check.
* xref:concept-docs:errors.adoc[Discussion document] on handling exceptions.
* Further reference material in the https://docs.couchbase.com/sdk-api/couchbase-c-client/index.html[API Guide].

