// tag::installation[]
== Platform support and installation

The Couchbase C SDK can be installed via apt or yum repositories on GNU/Linux; homebrew on Mac OS X; and <<install-windows,binary archives for Microsoft Windows>>.
It may also be https://github.com/couchbase/libcouchbase[built from source^] on any of the platforms mentioned above, and more.


== Installing on GNU/Linux

The various Linux distributions contain the following packages:

* ``**libcouchbase3**``: The core library package.
* ``**libcouchbase-dev**`` (or ``**libcouchbase-devel**``): The development package, required if building SDKs which depend on the C SDK.
* ``**libcouchbase3-tools**``: The command line utilities (`*cbc*` and others).
* ``**libcouchbase3-libevent**``: Optional but recommended component for I/O performance. Can also be used to integrate with libevent (see xref:howtos:concurrent-async-apis.adoc[Asynchronous Programming]).
* ``**libcouchbase3-libev**``: Optional, for use with applications that make use of event loop integration with libev (see xref:howtos:concurrent-async-apis.adoc[Asynchronous Programming]).
To install the C SDK from a static binary package or by manually configuring the repositories, you can use the following procedures.

=== Configuring yum repositories (CentOS, Redhat)

This section assumes you know how to add an external http://yum.baseurl.org/[yum] repository and Linux quick start explains the steps it will perform on your distribution.
To configure the repository:

. Find the appropriate repository location for your distribution in the following table.

[cols="1,1,3"]
|===
| Version | Architecture | Repository
| Amazon Linux 2     | 64-bit | \https://packages.couchbase.com/clients/c/repos/rpm/amzn2/x86_64
| Enterprise Linux 8 | 64-bit | \https://packages.couchbase.com/clients/c/repos/rpm/el8/x86_64
| Enterprise Linux 7 | 64-bit | \https://packages.couchbase.com/clients/c/repos/rpm/el7/x86_64
|===

. Create a `couchbase.repo` file in your `/etc/yum.repos.d` directory.  It should look similar to the following:

[source,toml]
----
[couchbase]
enabled = 1
name = libcouchbase package for centos8 x86_64
baseurl = https://packages.couchbase.com/clients/c/repos/rpm/el8/x86_64
gpgcheck = 1
gpgkey = https://packages.couchbase.com/clients/c/repos/rpm/couchbase.key
----

=== Configuring APT repositories (Debian, Ubuntu)

This section assumes some knowledge of https://wiki.debian.org/Apt[apt] and Linux quick start explains the steps it will perform on your distribution.
To configure the repository:

. Download the Couchbase GPG key from https://packages.couchbase.com/clients/c/repos/deb/couchbase.key
. Add the key to the list of trusted package keys.
Use the `apt-key add` command. For example, ``apt-key add couchbase.key``.
. Create a couchbase.list file in ``/etc/apt/sources.list.d``.
The file should contain the repository for your distribution.
Repositories are available for the following distributions:

[cols=".<2,.^9"]
|===
| Distribution            | Repository Entry
| Ubuntu 16.04 ("xenial") | ``deb \https://packages.couchbase.com/clients/c/repos/deb/ubuntu1604 xenial xenial/main``
| Ubuntu 18.04 ("bionic") | ``deb \https://packages.couchbase.com/clients/c/repos/deb/ubuntu1804 bionic bionic/main``
| Ubuntu 20.04 ("focal")  | ``deb \https://packages.couchbase.com/clients/c/repos/deb/ubuntu2004 focal focal/main``
| Debian 9 ("stretch")    | ``deb \https://packages.couchbase.com/clients/c/repos/deb/debian9 stretch stretch/main``
| Debian 10 ("buster")    | ``deb \https://packages.couchbase.com/clients/c/repos/deb/debian10 buster buster/main``
|===

Note that only Ubuntu LTS (long term support) releases are supported.
You may try to use an LTS repository for a non-LTS version, but success is not guaranteed.

Now that you have the repository configured, refresh the cache then check to see that you have been successful:

====
[source,console]
----
$ sudo apt update
----

[source,console]
----
$ sudo apt search libcouchbase
----
====

You should see something like:

[source,console]
----
libcouchbase-dbg - library for the Couchbase protocol, debug symbols
libcouchbase-dev - library for the Couchbase protocol, development files
libcouchbase3 - library for the Couchbase protocol, core files
libcouchbase3-libev - library for the Couchbase protocol (libev backend)
libcouchbase3-libevent - library for the Couchbase protocol (libevent backend)
libcouchbase3-tools - library for the Couchbase protocol
----

Now, install `libcouchbase3`, and any other packages that you need for development:

[source,console]
----
$ sudo apt install libcouchbase3 libcouchbase-dev libcouchbase3-tools libcouchbase-dbg libcouchbase3-libev libcouchbase3-libevent
----

For CentOS and Red Hat, the equivalent commands are:

====
[source,console]
----
$ sudo yum check-update
----

[source,console]
----
$ sudo yum search libcouchbase
----

[source,console]
----
$ sudo yum install libcouchbase3 libcouchbase-devel libcouchbase3-tools libcouchbase3-libevent
----
====


=== Installing binary packages without a repository

You can install standalone packages by downloading a tarball containing the necessary binary packages for your platform.

*Installing RPMs*

The following commands show steps to execute on *CentOS 8* box, see table below for other RPM-based distributions.

====
[source,console]
----
$ curl -O https://packages.couchbase.com/clients/c/libcouchbase-3.0.7_centos8_x86_64.tar
----

[source,console]
----
$ tar xf libcouchbase-3.0.7_centos8_x86_64.tar
----

[source,console]
----
$ cd libcouchbase-3.0.7_centos8_x86_64
----

[source,console]
----
$ sudo yum install -y libcouchbase3{-tools,-libevent,}-3.0.7*.rpm libcouchbase-devel-*.rpm
----

[source,console]
----
> ...
> Installed:
>   libcouchbase3-tools-3.0.7-1.el8.x86_64
>   libcouchbase3-libevent-3.0.7-1.el8.x86_64
>   libcouchbase3-3.0.7-1.el8.x86_64
>   libcouchbase-devel-3.0.7-1.el8.x86_64
>
> Complete!
----
====

*Installing DEBs*

The following commands show steps to execute on *Debian 10 (buster)* box, see table below for other DEB-based distributions.

====
[source,console]
----
$ curl -O https://packages.couchbase.com/clients/c/libcouchbase-3.0.7_debian10_buster_amd64.tar
----

[source,console]
----
$ tar xf libcouchbase-3.0.7_debian10_buster_amd64.tar
----

[source,console]
----
$ cd libcouchbase-3.0.7_debian10_buster_amd64
----

[source,console]
----
$ sudo apt install libevent-core-2.1
----

[source,console]
----
$ sudo dpkg -i libcouchbase3{-tools,-libevent,}_3.0.7*.deb libcouchbase-dev*.deb
> Selecting previously unselected package libcouchbase3-tools.
> (Reading database ... 7165 files and directories currently installed.)
> Preparing to unpack libcouchbase3-tools_3.0.7-1_amd64.deb ...
> Unpacking libcouchbase3-tools (3.0.7-1) ...
> Selecting previously unselected package libcouchbase3-libevent:amd64.
> Preparing to unpack libcouchbase3-libevent_3.0.7-1_amd64.deb ...
> Unpacking libcouchbase3-libevent:amd64 (3.0.7-1) ...
> Selecting previously unselected package libcouchbase3:amd64.
> Preparing to unpack libcouchbase3_3.0.7-1_amd64.deb ...
> Unpacking libcouchbase3:amd64 (3.0.7-1) ...
> Selecting previously unselected package libcouchbase-dev:amd64.
> Preparing to unpack libcouchbase-dev_3.0.7-1_amd64.deb ...
> Unpacking libcouchbase-dev:amd64 (3.0.7-1) ...
> Setting up libcouchbase3:amd64 (3.0.7-1) ...
> Setting up libcouchbase-dev:amd64 (3.0.7-1) ...
> Setting up libcouchbase3-libevent:amd64 (3.0.7-1) ...
> Setting up libcouchbase3-tools (3.0.7-1) ...
> Processing triggers for libc-bin (2.28-10) ...
----
====


== Installation from source

You may install the library from source either by downloading a source archive, or by checking out the https://github.com/couchbase/libcouchbase[git repository].
Follow the instructions in the archive's https://github.com/couchbase/libcouchbase/blob/master/README.markdown[README] for further instructions.

== Installation on Mac OS X

To install the library on Mac OS X, first install the de-facto package manager for OS X: http://brew.sh/[homebrew^].
Once _homebrew_ is configured:

====
[source,console]
----
$ brew update # get list of latest packages
----

[source,console]
----
$ brew install libcouchbase
----
====

To install development files and command line tools on Mac OS, follow the instructions for https://github.com/couchbase/libcouchbase/blob/master/README.markdown#building-on-unix-like-systems[installing from source].


[#install-windows]
== Windows Installation

Windows binary packages can be found as downloads for each version listed on the xref:../../project-docs/pages/sdk-release-notes.adoc[Release Notes and Archives page].
Included are the header files, release and debug variants of the DLLs and import libraries, and release and debug variants of the command line tools.
Note that the C SDK does not have any preferred installation path, and it is up to you to determine where to place ``libcouchbase.dll``.

Be sure to select the proper package for the compiler and architecture your application is using.

[NOTE]
====
If there are no binaries available for your Visual Studio version, then using a binary from any other Visual Studio version is _likely_ to work.
Most of the issues related to mixing Visual Studio binary versions involve changing and incompatible C++ APIs or incompatible C Runtime (CRT) objects and functions.
Since the Couchbase C SDK does not expose a C++ API, and since it does not directly expose any CRT functionality, it should be safe for use so long as your application can link to the library at compile-time.
The windows runtime linker will ensure that each binary is using the appropriate version of the Visual C Runtime (``MSVCRT.DLL``).
====

If for some reason you cannot use any of the prebuilt Windows binaries, follow the instructions in xref:#installation-from-source[__installation from source__ (above)] to build on Windows.


== Verifying Installed Package

The easiest way to verify installed package is to check its version using cbc tools. It requires package *libcouchbase3-tools* installed on Linux systems, for Windows *cbc.exe* included in the zip archive.
To verify the client run *cbc version* (*cbc.exe version* on Windows). Below is the output from version 3.0.7 on CentOS 8. It shows version along with git commit numbers. Then it prints default directory where IO plugins installed and enumerates the currently installed and available plugins. After that it reports whether OpenSSL linked to this particular version of libcouchbase, and displays the version number if it is accessible.

[source,console]
----
$ cbc version
cbc:
  Runtime: Version=3.0.7, Changeset=d2d3666e269b41413408aaae96eb289f1cb4f8ec
  Headers: Version=3.0.7, Changeset=d2d3666e269b41413408aaae96eb289f1cb4f8ec
  Build Timestamp: 2020-12-16 09:52:06
  Default plugin directory: /usr/lib64/libcouchbase
  IO: Default=libevent, Current=libevent, Accessible=libevent,select
  SSL Runtime: OpenSSL 1.1.1c FIPS  28 May 2019
  SSL Headers: OpenSSL 1.1.1g FIPS  21 Apr 2020
  Snappy: 1.1.1
  Tracing: SUPPORTED
  System: Linux-4.15.0-91-generic; x86_64
  CC: GNU 8.3.1; -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-strict-aliasing -ggdb3 -pthread
  CXX: GNU 8.3.1; -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-strict-aliasing -ggdb3 -pthread
----
// end::installation[]
