= Buckets and Clusters
:navtitle: Buckets & Clusters
:page-topic-type: concept
:page-aliases: managing-clusters

[abstract]
The Couchbase C SDK provides an API for managing a Couchbase cluster programmatically.

include::6.5@sdk:shared:partial$clusters-buckets.adoc[tag=management]

== Creating and Removing Buckets

To create or delete a bucket using the REST API :

[source,c]
----
    lcb_CMDHTTP htcmd = {};
    LCB_CMD_SET_KEY(&htcmd, path.c_str(), path.size());
    htcmd.body = params.c_str();
    htcmd.nbody = params.size();
    htcmd.content_type = "application/x-www-form-urlencoded";
    htcmd.method = LCB_HTTP_METHOD_POST;
    htcmd.type = LCB_HTTP_TYPE_MANAGEMENT;
    htcmd.username = "Administrator";
    htcmd.password = "password";
    lcb_http3(instance, NULL, &htcmd);
    lcb_wait(instance);

    // now remove the bucket
    memset(&htcmd, 0, sizeof htcmd);
    path = "/pools/default/buckets/newBucket";
    LCB_CMD_SET_KEY(&htcmd, path.c_str(), path.size());
    htcmd.method = LCB_HTTP_METHOD_DELETE;
    htcmd.type = LCB_HTTP_TYPE_MANAGEMENT;
    htcmd.username = "Administrator";
    htcmd.password = "password";
    lcb_http3(instance, NULL, &htcmd);
    lcb_wait(instance);
----
////
Management operations in the C SDK may be performed through several interfaces depending on the object:

== Creating and Removing Buckets

To create or delete a bucket, call the bucket manager with the `buckets()` call on the cluster:

[source,java]
----
Cluster cluster = Cluster.connect("127.0.0.1", "user", "123456");
BucketManager manager = cluster.buckets();
manager.createBucket(bucketSettings);
----

// The `BucketSettings` can be created via a builder, [.api]`DefaultBucketSettings.builder()`.
This class is also used to expose information about an existing bucket (`manager.getBucket(string)`) or to update an existing bucket (`manager.updateBucket(bucketSettings)`).

The default Collection & Default Scope will be used automatically.
////
