= Browser and CLI Access
:description: Web and command line interfaces to Couchbase Server are available.
:page-topic-type: landing-page
:page-aliases: ROOT:webui-cli-access

[abstract]
{description}
Installation of the cbc command line tools is covered here, and links are given to the man pages, for full usage instuctions.
The Web console is documented in the Server docs.


Web and command line interfaces to Couchbase Server are available.
The cbc command line tools are a part of libcouchbase, with installation documented below, whilst Web console access is provided in Couchbase Server -- xref:#couchbase-web-console-document-query-access[see links].



== Command Line

You can access documents in Couchbase using command line interfaces.
Libcouchbase (LCB), our C SDK, includes the `cbc` tools.
This is in addition to the xref:server:cli:cli-intro.adoc[command line tools] integrated into Couchbase Server to manage the cluster and to collect diagnostics.


A version of LCB ships with some releases of Couchbase Server, but here we are assuming you want to install the command line tools on a client machine, or to acquire the latest version.
To install the cbc command line tools, install _libcouchbase_:

If you already have LCB installed, then xref:#cbc-tools[skip ahead to our summary of tools included on cbc].

// installation instructions
include::partial$installation.adoc[]


== cbc Tools

The `cbc` tools are documented in their respective `man` pages.
Links to online versions in the latest API docs are provided below.
They are fairly stable utilities, and do not tend to change across LCB versions,
however, you can see all recent updates https://github.com/couchbase/libcouchbase/tree/master/doc/man[on their GitHub page].

* {lcb_api_link}/md_doc_cbc.html[cbc]:
`cbc` is a utility for communicating with a Couchbase cluster.
* {lcb_api_link}/md_doc_cbcrc.html[cbcrc]:
`cbcrc` is an optional configuration file used to provide default values for the `cbc` and `cbc-pillowfight` utilities.
* {lcb_api_link}/md_doc_cbc_subdoc.html[cbc-subdoc]:
`cbc-subdoc` runs an interactive shell with commands from subdocument API.
* {lcb_api_link}/md_doc_cbc_pillowfight.html[cbc-pillowfight]:
`cbc-pillowfight` is a stress test for Couchbase Client and Cluster.
It creates a specified number of threads each looping and performing get and set operations within the cluster.
* {lcb_api_link}/md_doc_cbc_n1qlback.html[cbc-n1qlback]:
`cbc-n1qlback` creates a specified number of threads each executing a set of user defined queries.


== Couchbase Web Console Document & Query Access

You can use the Couchbase Web Console to view, edit, and create JSON documents up to 256KB in size -- see the xref:7.0@server:manage:manage-ui/manage-ui.adoc[Couchbase Web Console] in the Server docs.

You can also use the xref:7.0@server:tools:query-workbench.adoc[Query Workbench] to issue N1QL queries using the web console.
