= Couchbase C SDK {lcb_current_version}
:page-type: landing-page
:page-layout: landing-page-top-level-sdk
:page-meta-zd-site-verification: l6235mojs6qcq5ox3z6gfa
:page-role: tiles
:!sectids:
// :page-aliases: ROOT:c-sdk.sdoc


++++
<div class="card-row two-column-row">
++++


[.column]
====== {empty}
[.content]
The Couchbase C client, _libcouchbase_ (LCB), enables you to interact with a Couchbase Server cluster from the C language.
It is also used by the Node.js, PHP, and Python SDKs to communicate with the Couchbase Server.


[.column]
[.content]
[source,c++]
----
const char *connection_string = "couchbase://192.168.56.101,192.168.56.102";

lcb_CREATEOPTS *options = NULL;
lcb_createopts_create(&options, LCB_TYPE_CLUSTER);
lcb_createopts_connstr(options, connection_string, strlen(connection_string));
----

++++
</div>
++++



[.column]
====== {empty}

== Couchbase C SDK {lcb_current_version}

++++
<div class="card-row three-column-row">
++++


[.column]
====== {empty}
.Getting Started

[.content]
Dive right in with a xref:start-using-sdk.adoc[quick install and Hello World].
// Try out our xref:sample-application.adoc[Travel Sample Application].
// And take a look at the xref:howtos:working-with-collections.adoc[developer preview of Collections].


[.column]
====== {empty}
.Practical Howto Docs

[.content]
Connect to our services -- xref:howtos:kv-operations.adoc[data (KV)];
xref:howtos:n1ql-queries-with-sdk.adoc[Query] --
and the xref:howtos:subdocument-operations.adoc[Sub-Document API].
////
xref:howtos:full-text-searching-with-sdk.adoc[Search];
xref:howtos:analytics-using-sdk.adoc[Analytics];
xref:howtos:view-queries-with-sdk.adoc[Views] --
////
And follow the xref:howtos:concurrent-document-mutations.adoc[Concurrent Document Mutations] howto guide.

[.column]
====== {empty}
.Reference Guides

[.content]
The documentation supplements the practical Howto docs with references and xref:concept-docs:concepts.adoc[concept guides], for those who prefer a broader understanding before diving in and coding.
[]
{lcb_api_link}/index.html[API Docs^]


[.column]
====== {empty}
.What's Hot?

[.content]
Leverage the new Couchbase Server Scopes and Collection features to build multi-tenant micro-service application.

// * xref:1.0@cxx-txns::distributed-acid-transactions-from-the-sdk.adoc[{cpp} Distributed ACID Transactions from the C SDK]
* xref:cbc.adoc[LCB includes our command line tools]


[.column]
====== {empty}
.About

[.content]
Those useful nuts-and-bolts guides to
xref:project-docs:compatibility.adoc[compatibility tables];
xref:project-docs:sdk-release-notes.adoc[release notes];
xref:project-docs:get-involved.adoc[contribution guide].
// and the
// xref:project-docs:migrating-sdk-code-to-3.n.adoc[migration guide] for moving to the 3.0 API.

[.column]
====== {empty}
.Community

[.content]
For community help, visit the https://forums.couchbase.com/c/c-sdk/7[Couchbase forums^].
//  -- in the https://blog.couchbase.com/[Couchbase Blog^] there are examples covering everything from ????

++++
</div>
++++

include::{version-common}@sdk:shared:partial$archive.adoc[tag=link]


include::{version-common}@sdk:shared:partial$columnar-available.adoc[tag=initial-availability-o]


////
== icon:code[] Couchbase Operational Cluster Feature Compatibility

// include::project-docs:deployment.adoc[tag=feature-compat]


All of the SDKs have API compatibility with most of the features in Couchbase Operational Clusters --
whether self-managed, or Capella.
The following table covers possible exceptions, and gives the version of the C SDK (libcouchbase) and Couchbase Server with which some features were introduced.

Note that the xref:cxx:hello-world:overview.adoc[Couchbase {cpp} SDK] is a more featureful SDK --
with broader coverage of recent Couchbase Server features --
as well as a more modern API.


.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="8,5,5,5"]
|===
| | Server 7.2 | Server 7.6.x  | Server 8.0

| KV Range Scan
| N/A
2+| Unsupported

| Zone aware replica reads
| N/A
2+| 3.3.14

| Vector Search with Search Vector Index
| N/A
2+| Unsupported

| Vector Query using Hyperscale Vector Index
2+| N/A
| Unsupported ①

| Vector Query using Composite (GSI & vector) index
2+| N/A
| Unsupported ①

| Distributed ACID Transactions  
3+| Unsupported

| DNS SRV refresh for serverless environments (AWS Lambda, Azure Functions, and GCP Functions)
3+| Unsupported

| Circuit Breakers
3+| Unsupported

| OTel 
3+| Unsupported

| Field Level Encryption 
3+| Unsupported

| Cloud Native Gateway  
3+| Unsupported
|===

<1> As part of the standard SDK {sqlpp} API, it should be compatible with all versions of the SDK -- but it has not been tested.
////
