= Couchbase C SDK 3.1
:page-type: landing-page
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:!sectids:
// :page-aliases: ROOT:c-sdk.sdoc


++++
<div class="card-row two-column-row">
++++


[.column]
====== {empty}
[.content]
The Couchbase C client, _libcouchbase_ (LCB), enables you to interact with a Couchbase Server cluster from the C language.
It is also used by the Node.js, PHP, and Python SDKs to communicate with the Couchbase Server.


[.column]
[.content]
[source,c++]
----
const char *connection_string = "couchbase://192.168.56.101,192.168.56.102";

lcb_CREATEOPTS *options = NULL;
lcb_createopts_create(&options, LCB_TYPE_CLUSTER);
lcb_createopts_connstr(options, connection_string, strlen(connection_string));
----

++++
</div>
++++



[.column]
====== {empty}

== Couchbase C SDK 3.1

++++
<div class="card-row three-column-row">
++++


[.column]
====== {empty}
.Getting Started

[.content]
Dive right in with a xref:start-using-sdk.adoc[quick install and Hello World].
// Try out our xref:sample-application.adoc[Travel Sample Application].
// And take a look at the xref:howtos:working-with-collections.adoc[developer preview of Collections].


[.column]
====== {empty}
.Practical Howto Docs

[.content]
Connect to our services -- xref:howtos:kv-operations.adoc[data (KV)];
xref:howtos:n1ql-queries-with-sdk.adoc[Query] --
and the xref:howtos:subdocument-operations.adoc[Sub-Document API].
////
xref:howtos:full-text-searching-with-sdk.adoc[Search];
xref:howtos:analytics-using-sdk.adoc[Analytics];
xref:howtos:view-queries-with-sdk.adoc[Views] --
////
And follow the xref:howtos:concurrent-document-mutations.adoc[Concurrent Document Mutations] howto guide.

[.column]
====== {empty}
.Reference Guides

[.content]
The documentation supplements the practical Howto docs with references and xref:concept-docs:concepts.adoc[concept guides], for those who prefer a broader understanding before diving in and coding.
[]
https://docs.couchbase.com/sdk-api/couchbase-c-client/index.html[API Docs^]


[.column]
====== {empty}
.What's Hot?

[.content]
Libcouchbase 3.x is a complete rewrite, with a streamlined API.

* xref:1.0@cxx-txns::distributed-acid-transactions-from-the-sdk.adoc[{cpp} Distributed ACID Transactions from the C SDK]
* xref:cbc.adoc[LCB includes our command line tools]
* xref:concept-docs:collections.adoc[Works with our Collections Developer Preview]
* xref:concept-docs:durability-replication-failure-considerations.adoc[New Synchronous Write Durability]



[.column]
====== {empty}
.About

[.content]
Those useful nuts-and-bolts guides to
xref:project-docs:compatibility.adoc[compatibility tables];
xref:project-docs:sdk-release-notes.adoc[release notes];
xref:project-docs:get-involved.adoc[contribution guide].
// and the
// xref:project-docs:migrating-sdk-code-to-3.n.adoc[migration guide] for moving to the 3.0 API.

[.column]
====== {empty}
.Community

[.content]
For community help, visit the https://forums.couchbase.com/c/c-sdk/7[Couchbase forums^].
//  -- in the https://blog.couchbase.com/[Couchbase Blog^] there are examples covering everything from ????

++++
</div>
++++
