= Install and Start Using the C SDK with Couchbase Server
:navtitle: Start Using the SDK

[abstract]
The Couchbase C SDK (libcouchbase - LCB) enables you to interact with a Couchbase Server cluster from the C language.
It is also used by the Node.js, PHP, and Python SDKs to communicate with the Couchbase Server.

include::partial$alpha-warning.adoc[]

== Installing the SDK

// A necessarily longer section than that of most of the other clients.


////

Time to incorporate this?
(in updated form?)

Assuming git and Visual Studio 2010 are installed, from a CMD shell, do:

C:\> git clone git://github.com/couchbase/libcouchbase.git
C:\> mkdir lcb-build
C:\> cd lcb-build
C:\> cmake -G "Visual Studio 10" ..\libcouchbase
C:\> cmake --build .
This will generate and build a Visual Studio .sln file.

Windows builds are known to work on Visual Studio versions 2008, 2010 and 2012.

If you wish to link against OpenSSL, you should set the value of OPENSSL_ROOT_DIR to the location of the installation path, as described here
https://github.com/Kitware/CMake/blob/master/Modules/FindOpenSSL.cmake

////




== Hello Couchbase

// Needs localising to C

Now you have the .NET client installed grab the code from link:href://devguideexamples or open a fresh project in VS Code and try out the following:

[source,csharp]
----
var config = new Configuration
{
    Servers = new List<Uri> {new Uri("http://10.112.180.101:8091")},
    UserName = "username",
    Password = "password"
};
----

Couchbase uses xref:6.5@server:learn/security:roles.adoc[Role Based Access Control (RBAC) to control access to resources.
Here we will use the _Full Admin_ role created during installation of the Couchbase Data Platform.
For production client code, you will want to use xref:3.0dp1@net-sdk:howtos:managing-connections.adoc#rbac[more appropriate, restrictive settings], but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _localhost_.


// initialize cluster

[source,csharp]
----
var cluster = new Cluster();
await cluster.Initialize(config)

// possible alternative (doesn't currently work)
//var cluster = await Cluster.Connect(config);
----

Connection to the cluster is initialized by
// to be filled in when above is clarified.

// Mike: ideal is for socket / http client init during cluster connect, but we typically require a bucket, so may be delated until a bucket instance is requested, like it is in 2.x.

[source,csharp]
----
// get a bucket reference
var bucket = await cluster.Bucket("bucket-name");
----

If you installed the travel sample data bucket, substitute _travel-sample_ for _bucket-name_.

[source,csharp]
----
// get a collection reference
var collection = await bucket.DefaultCollection;
var myCollection = bucket.Scope("my-collection");
----

The 3.0 SDK is ready for the introduction of xref:#[Collections] in Cheshire Cat, the next release of the Couchbase Data Platform.
The latest release, Mad Hatter, brings a limited _Developer Preview_ of Collections, allowing Documents to be grouped by purpose or theme, according to specified _Scope_.
Here we will use the `DefaultCollection`, which covers the whole Bucket.

[source,csharp]
----
// upsert document
var upsertResult = await collection.Binary.Upsert("my-document", new {name = "mike"});

// get document
var getResult = await collection.Binary.Get("my-document");
----

The `Binary` service is a wrapper for the core Key Value (KV) database service.
KV Operations are described in detail on the xref:net-sdk:howtos:kv-operations.adoc[KV Operations page].
Now that you know the basics, you may wish to go straight to that page -- or first see a complete worked example of using the Couchbase .NET client, our xref:3.0dp1@sample-application.adoc[Travel Sample Application].

== Additional Resources

The API reference is generated for each release and the latest can be found http://docs.couchbase.com/sdk-api/couchbase-c-client/[here].
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

// xref:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the C SDK.
The C SDK source code is available on https://github.com/couchbase/libcouchbase[GitHub].
